### ISSUE TITLE
Null direction at the end of a simulation.

### ISSUE THREAD

**Issue by orabpar** [aortiza/icenumerics#10]
Occasionally, at the end of a simulation, a colloid can be found at the exact center of the trap. That results in a null direction for the colloid.
This situation raises an [error](https://user-images.githubusercontent.com/42385295/80393094-4ca93280-88b0-11ea-9003-9cb166be60de.PNG) when passing colloids to vertices in "vertices.py".

**Comment by aortiza** [comment]
I think this has been solved by 573a49136f681b76e6edb146282890ab710d1f7f
