### ISSUE TITLE
Vertex classification does not work properly in multitrap branch

### ISSUE THREAD

**Issue by crodriga** [aortiza/icenumerics#13]
In the multitrap branch, traps could have different lengths and center positions, thus traps are not in the same lattice and do not have the same trap separation. Due to that, vertices in the last dataframe are not properly classified. 

I have patch the issue by chaenging a bit the function from_neighbors_get_nearest_neighbors() in line 85 of vertices.py file:

```
def from_neighbors_get_nearest_neighbors(NeighborPairs):
    # This function takes a list of Delaunay Neighbor Pairs and returns only those which are close to the minimum distance.
    NeighborPairs['Distance']=np.around(NeighborPairs['Distance'],decimals=4)
    #print(NeighborPairs['Distance'])
    #NeighborPairs = NeighborPairs[NeighborPairs['Distance']<=np.min(NeighborPairs['Distance'])*1.1]
    NeighborPairs = NeighborPairs[NeighborPairs['Distance']<=21.2132*1.1]
    
    return NeighborPairs
```
I just printed the Neighborpairs['Distance'] and manually choose the one that maps the inner vertices.

**Comment by aortiza** [comment]
This was solved in 573a49136f681b76e6edb146282890ab710d1f7f.
