### ISSUE TITLE
'progress_func' is not defined

### ISSUE THREAD

**Issue by crodriga** [aortiza/icenumerics#14]
The function v.trj_to_vertices() is not working properly, it seems that in the new merge some function gets lost and is not included in the new version. Hence, the match between trajectories (.lammpstrj files) and vertices now is unavailable. 

I left a jupyter notebook and a .lammpstrj file in Drive located at:

DegenerateIce>BidisperseSystems>Issue Github

[https://drive.google.com/drive/u/0/folders/10MQ73BFr2lgPcI3b1sf0w26xDzczg5I8](url)

**Comment by aortiza** [comment]
This is very likely a problem with the way we call the tqdm progress bar function. I think before I was trying to change the function depending on whether tqdm was installed or not. To fix it we must change `progress_func()` to `tqdm.tqdm()`

**Comment by aortiza** [comment]
This was fixed in commit 573a49136f681b76e6edb146282890ab710d1f7f by adding tqdm to vertices.py. Now it's a dependency.
