### ISSUE TITLE
Forces in the simulation documentation is not up to date.

### ISSUE THREAD

**Issue by crodriga** [aortiza/icenumerics#16]
The documentation of forces in the simulation is not up to date:  https://aortiza.github.io/icenumerics/OtherNotebooks/ForcesOfTheSimulation.html.

We corrected the documentation and created a new checking script in: https://github.com/crodriga/PROJECT_CairoLattice/blob/master/Scripts/Script-6.0_CheckingHillDefinition.ipynb

**Comment by aortiza** [comment]
Hi Carolina,

It's been a while since you raised this issue. Is it still wrong? Can you tell me what is wrong in the current version of the docs?

**Comment by crodriga** [comment]
Hi Antonio, 

If I am not mistaken, what is confusing in your documentation and not up to date is the definition of the height in the trap definition. In the cell nº [6] the height is defined with units pN*nm, and you change it to pN/nm. 

In the current version, the height is defined in pN*nm and accounts for the energy barrier of the double well trap. And is related to the stiffness of the hill (k_hill) with the equation:

height = (k_hill/2)* (trap_sep/2)**2

But please verify it!

**Comment by aortiza** [comment]
I think this is fixed.
