### ISSUE TITLE
pint version

### ISSUE THREAD

**Issue by Raul-lab** [aortiza/icenumerics#9]
with pint 0.11 the following error appears; to solve it try 
conda install -c conda-forge pint=0.9

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-0faab950c549> in <module>
      1 col.run_simulation()
----> 2 col.load_simulation()

~\Desktop\Tutorial\icenumerics\icenumerics\colloidalice.py in load_simulation(self, sl)
    372         self.trj = self.sim.load(read_trj = True, sl = sl)
    373         self.frames = self.trj.index.get_level_values("frame").unique()
--> 374         self.set_state_from_frame(frame = -1)
    375 
    376     def set_state_from_frame(self, frame):

~\Desktop\Tutorial\icenumerics\icenumerics\colloidalice.py in set_state_from_frame(self, frame)
    380         for i,c in enumerate(self):
    381             c.colloid = self.trj.loc[idx[frame,i+1],["x","y","z"]].values*ureg.um - c.center
--> 382             c.direction = c.direction * np.sign(np.dot(c.colloid,c.direction))
    383 
    384         return self

TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'sign'>, '__call__', <Quantity(5.296799659729004, 'micrometer')>): 'Quantity'

**Comment by aortiza** [comment]
This error came from doing the numpy dot product of c.colloid, which has units, and c.direction which has no units. 

Line 382 was fixed by using the magnitude of c.colloid. It will be included in the next commit
